//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DerpibooruWallpaper.Localization {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DerpibooruWallpaper.Localization.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 API Key 的本地化字符串。
        /// </summary>
        internal static string APIKey {
            get {
                return ResourceManager.GetString("APIKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All API requests are currently paused
        ///Please check ErrorLog.log for information.
        ///Please restart the program to recover. 的本地化字符串。
        /// </summary>
        internal static string APIRequestPaused {
            get {
                return ResourceManager.GetString("APIRequestPaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Attention 的本地化字符串。
        /// </summary>
        internal static string Attention {
            get {
                return ResourceManager.GetString("Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Derpibooru has banned you from using this API.
        ///Your account or IP address may have been banned.
        ///Server HTTP response code: {0} {1}
        ///program will now pause all API requests until restart 的本地化字符串。
        /// </summary>
        internal static string BannedFromDerpibooru {
            get {
                return ResourceManager.GetString("BannedFromDerpibooru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot verify API key 的本地化字符串。
        /// </summary>
        internal static string CannotVerifyAPIKey {
            get {
                return ResourceManager.GetString("CannotVerifyAPIKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change Wallpaper 的本地化字符串。
        /// </summary>
        internal static string ChangeWallpaper {
            get {
                return ResourceManager.GetString("ChangeWallpaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to close without saving? 的本地化字符串。
        /// </summary>
        internal static string CloseWithoutSavingWarning {
            get {
                return ResourceManager.GetString("CloseWithoutSavingWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connection Settings 的本地化字符串。
        /// </summary>
        internal static string ConnectionSettings {
            get {
                return ResourceManager.GetString("ConnectionSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Days 的本地化字符串。
        /// </summary>
        internal static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Derpibooru Wallpaper Settings 的本地化字符串。
        /// </summary>
        internal static string DerpibooruWallpaperSettings {
            get {
                return ResourceManager.GetString("DerpibooruWallpaperSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Empty API key 的本地化字符串。
        /// </summary>
        internal static string EmptyAPIKey {
            get {
                return ResourceManager.GetString("EmptyAPIKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 error message 的本地化字符串。
        /// </summary>
        internal static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An error occured while verifying your API key 的本地化字符串。
        /// </summary>
        internal static string ErrorVerifyingAPIKey {
            get {
                return ResourceManager.GetString("ErrorVerifyingAPIKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit 的本地化字符串。
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to open registry key, cannot setup launch on system startup 的本地化字符串。
        /// </summary>
        internal static string FailedToOpenRegistryKeyForLaunchOnStartup {
            get {
                return ResourceManager.GetString("FailedToOpenRegistryKeyForLaunchOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to verify API key 的本地化字符串。
        /// </summary>
        internal static string FailedToVerifyAPIKey {
            get {
                return ResourceManager.GetString("FailedToVerifyAPIKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hours 的本地化字符串。
        /// </summary>
        internal static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Launch on system startup 的本地化字符串。
        /// </summary>
        internal static string LaunchOnSystemStartup {
            get {
                return ResourceManager.GetString("LaunchOnSystemStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Made by wd357dui
        ///Not associated with derpibooru developers, administrators or moderators.
        ///March, 2023 的本地化字符串。
        /// </summary>
        internal static string MadeBy {
            get {
                return ResourceManager.GetString("MadeBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minutes 的本地化字符串。
        /// </summary>
        internal static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No images found with current search parameters 的本地化字符串。
        /// </summary>
        internal static string NoImagesFoundWithCurrentSearchParameters {
            get {
                return ResourceManager.GetString("NoImagesFoundWithCurrentSearchParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Background task running, it&apos;s not safe to close the window yet 的本地化字符串。
        /// </summary>
        internal static string NotSafeToCloseYet {
            get {
                return ResourceManager.GetString("NotSafeToCloseYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This is not a valid API key 的本地化字符串。
        /// </summary>
        internal static string NotValidAPIKey {
            get {
                return ResourceManager.GetString("NotValidAPIKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open image folder 的本地化字符串。
        /// </summary>
        internal static string OpenImageFolder {
            get {
                return ResourceManager.GetString("OpenImageFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Override existing image files 的本地化字符串。
        /// </summary>
        internal static string OverrideExistingImageFiles {
            get {
                return ResourceManager.GetString("OverrideExistingImageFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Press {0} to save anyway 的本地化字符串。
        /// </summary>
        internal static string PressToSaveKeyAnyway {
            get {
                return ResourceManager.GetString("PressToSaveKeyAnyway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Press {0} to use this key anyway 的本地化字符串。
        /// </summary>
        internal static string PressToUseKeyAnyway {
            get {
                return ResourceManager.GetString("PressToUseKeyAnyway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Program Settings 的本地化字符串。
        /// </summary>
        internal static string ProgramSettings {
            get {
                return ResourceManager.GetString("ProgramSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search Parameters 的本地化字符串。
        /// </summary>
        internal static string SearchParameters {
            get {
                return ResourceManager.GetString("SearchParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select unit of time first (days/hours/minutes) 的本地化字符串。
        /// </summary>
        internal static string SelectUnitOfTimeFirst {
            get {
                return ResourceManager.GetString("SelectUnitOfTimeFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Server did not provide download link for image #{0} 的本地化字符串。
        /// </summary>
        internal static string ServerDidNotProvideFullLink {
            get {
                return ResourceManager.GetString("ServerDidNotProvideFullLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Server HTTP response code: {0} {1} 的本地化字符串。
        /// </summary>
        internal static string ServerResponseCode {
            get {
                return ResourceManager.GetString("ServerResponseCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please specify your API key before using 的本地化字符串。
        /// </summary>
        internal static string SpecifyYourAPIKey {
            get {
                return ResourceManager.GetString("SpecifyYourAPIKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Derpibooru is asking you to ease down..
        ///(You have been refreshing data too fast)
        ///Server HTTP response code: {0} {1} 的本地化字符串。
        /// </summary>
        internal static string TooManyRequests {
            get {
                return ResourceManager.GetString("TooManyRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Server responded with a status code I did not prepare for, but I do know that it&apos;s something wrong on the client side ({0} {1})
        ///program will now pause all API requests until restart 的本地化字符串。
        /// </summary>
        internal static string Unrecognized400 {
            get {
                return ResourceManager.GetString("Unrecognized400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Server responded with a status code I did not prepare for, but I do know that it&apos;s something wrong on the server side ({0} {1}) 的本地化字符串。
        /// </summary>
        internal static string Unrecognized500 {
            get {
                return ResourceManager.GetString("Unrecognized500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Server responded with a status code I did not prepare for ({0} {1}) 的本地化字符串。
        /// </summary>
        internal static string UnrecognizedStatusCode {
            get {
                return ResourceManager.GetString("UnrecognizedStatusCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You haven&apos;t saved your API key 的本地化字符串。
        /// </summary>
        internal static string UnsavedAPIKey {
            get {
                return ResourceManager.GetString("UnsavedAPIKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You haven&apos;t saved your search parameters 的本地化字符串。
        /// </summary>
        internal static string UnsavedSearchParams {
            get {
                return ResourceManager.GetString("UnsavedSearchParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You haven&apos;t saved your wallpaper changing interval 的本地化字符串。
        /// </summary>
        internal static string UnsavedWallpaperChangeInterval {
            get {
                return ResourceManager.GetString("UnsavedWallpaperChangeInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use HTTPS 的本地化字符串。
        /// </summary>
        internal static string UseHTTPS {
            get {
                return ResourceManager.GetString("UseHTTPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use system proxy 的本地化字符串。
        /// </summary>
        internal static string UseSystemProxy {
            get {
                return ResourceManager.GetString("UseSystemProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use Trixiebooru mirror 的本地化字符串。
        /// </summary>
        internal static string UseTrixiebooruMirror {
            get {
                return ResourceManager.GetString("UseTrixiebooruMirror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wait... 的本地化字符串。
        /// </summary>
        internal static string Wait {
            get {
                return ResourceManager.GetString("Wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wallpaper Change Interval 的本地化字符串。
        /// </summary>
        internal static string WallpaperChangeInterval {
            get {
                return ResourceManager.GetString("WallpaperChangeInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning 的本地化字符串。
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please go to your account settings page on derpibooru.org to see your API key 的本地化字符串。
        /// </summary>
        internal static string WhereToCheckYourAPIKey {
            get {
                return ResourceManager.GetString("WhereToCheckYourAPIKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your internet connection is fine, but Derpibooru servers are currently unavailable (503) 的本地化字符串。
        /// </summary>
        internal static string YourConnectionIsFineButDerpibooru503 {
            get {
                return ResourceManager.GetString("YourConnectionIsFineButDerpibooru503", resourceCulture);
            }
        }
    }
}
